#!/usr/bin/env python3
"""Apply the 2026-10-06 organic visibility consolidation.

This script is intentionally deterministic. It replaces catalogue-heavy entry
pages with two canonical offers, creates a proof portfolio and benchmark, then
marks non-canonical legacy HTML as noindex while retaining it for redirects and
historical access.
"""
from pathlib import Path
import json, re

ROOT = Path(__file__).resolve().parents[1]
BRAND = "AICloudStrategist"
BASE = "https://aicloudstrategist.com"

ORG = {
    "@context": "https://schema.org",
    "@type": "Organization",
    "@id": f"{BASE}/#organization",
    "name": BRAND,
    "alternateName": "AI Cloud Strategist",
    "legalName": "AICLOUDSTRATEGIST PRIVATE LIMITED",
    "identifier": {
        "@type": "PropertyValue",
        "propertyID": "Corporate Identity Number (India)",
        "value": "U62020DC2026PTC470945",
    },
    "foundingDate": "2026-04-29",
    "url": f"{BASE}/",
    "logo": f"{BASE}/assets/brand/aics-logo.svg",
    "description": "Independent production AI readiness and cloud AI economics reviews for mid-market and scale-up teams.",
    "email": "contact@aicloudstrategist.com",
    "telephone": "+91 80654 80898",
    "address": {
        "@type": "PostalAddress",
        "streetAddress": "Plot No. B-311, Kh. No. 36, Ground Floor, Block B, Bawana",
        "addressLocality": "Delhi",
        "addressRegion": "Delhi",
        "postalCode": "110039",
        "addressCountry": "IN",
    },
    "sameAs": [
        "https://github.com/support-aicloudstrategist/support-aicloudstrategist.github.io",
        "https://www.youtube.com/@aicloudstrategist",
        "https://dev.to/aicloudstrategist",
    ],
    "areaServed": ["India", "Worldwide"],
}

REVIEWER = {
    "@context": "https://schema.org",
    "@type": "Person",
    "@id": f"{BASE}/about/#review-owner",
    "name": "Anushka Bhattacharya",
    "jobTitle": "Director",
    "worksFor": {"@id": f"{BASE}/#organization"},
    "url": f"{BASE}/about/#review-owner",
    "knowsAbout": ["Production AI readiness", "AI operating controls", "Cloud and AI economics"],
}

def esc(value):
    return str(value).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace('"', "&quot;")

def shell(title, description, canonical, h1, eyebrow, lead, body, *, schema=None, lang="en-IN"):
    schemas = [ORG, REVIEWER]
    if schema: schemas.extend(schema if isinstance(schema, list) else [schema])
    ld = "".join(f'<script type="application/ld+json">{json.dumps(item, separators=(",", ":"))}</script>' for item in schemas)
    return f'''<!doctype html><html lang="{lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>{esc(title)}</title><meta name="description" content="{esc(description)}"><link rel="canonical" href="{canonical}"><meta name="robots" content="index,follow,max-image-preview:large">
<meta property="og:type" content="website"><meta property="og:site_name" content="{BRAND}"><meta property="og:title" content="{esc(title)}"><meta property="og:description" content="{esc(description)}"><meta property="og:url" content="{canonical}"><meta property="og:image" content="{BASE}/assets/brand/aics-growth-focus-og.png"><meta name="twitter:card" content="summary_large_image">
<link rel="icon" href="/favicon.svg"><link rel="apple-touch-icon" href="/assets/brand/aics-touch-icon.png"><link rel="stylesheet" href="/css/growth-focus.css?v=20261006b"><link rel="stylesheet" href="/css/visibility-focus.css?v=20261006b">{ld}<script defer src="/js/aics-analytics-shim.js?v=20261006b"></script><script defer src="/js/aics-conversion-tracking.js?v=20261006b"></script></head><body>
<header class="site-head"><nav class="wrap nav"><a class="brand" href="/" aria-label="AICloudStrategist home">AI<span>Cloud</span>Strategist</a><div class="links"><a href="/services/production-ai-readiness/">Production AI</a><a href="/services/cloud-ai-economics/">Cloud economics</a><a href="/portfolio/">Portfolio</a><a href="/resources/">Resources</a><a href="/pricing/">Pricing</a><a class="button" href="/free-business-review/">Request fit review</a></div></nav></header>
<main><section class="hero"><div class="wrap hero-grid"><div><span class="eyebrow">{esc(eyebrow)}</span><h1>{esc(h1)}</h1><p>{esc(lead)}</p><div class="actions"><a class="button" data-aics-cta="primary-fit-review" href="/free-business-review/">Request a fit review</a><a class="button secondary" href="#details">See the evidence</a></div></div><aside class="proof-card"><strong>Evidence policy</strong><p>Customer results are published only after measured delivery and written consent. Current portfolio items are labelled as self-tested methods, representative samples or public-source research.</p><a href="/portfolio/">Inspect the portfolio →</a></aside></div></section><div id="details">{body}</div></main>
<footer class="footer"><div class="wrap footer-grid"><div><strong>{BRAND}</strong><p>Production AI readiness and cloud AI economics.</p><small>AICLOUDSTRATEGIST PRIVATE LIMITED · CIN U62020DC2026PTC470945</small></div><div><a href="/about/">About and review ownership</a><br><a href="/company-details/">Registered company details</a><br><a href="/visibility-methodology/">Visibility methodology</a></div><div><a href="mailto:contact@aicloudstrategist.com">contact@aicloudstrategist.com</a><br><a href="/privacy">Privacy</a> · <a href="/terms">Terms</a></div></div></footer></body></html>'''

HOME_BODY = '''
<section class="section"><div class="wrap"><span class="badge">Two commercial decisions</span><h2>Start with the decision that is blocking progress.</h2><div class="grid-2">
<article class="card"><p class="kicker">01 · Before production</p><h3>Production AI Readiness Diagnostic</h3><p>For an AI pilot, agent or workflow that works in a demonstration but lacks complete evidence for evaluation, authority, security, recovery and operating ownership.</p><ul><li>Evidence and failure-mode register</li><li>Human authority and escalation matrix</li><li>Release, remediate or hold recommendation</li></ul><a class="button" href="/services/production-ai-readiness/">Inspect the diagnostic</a></article>
<article class="card"><p class="kicker">02 · Before more spend</p><h3>Cloud &amp; AI Economics Review</h3><p>For teams with rising cloud, model, GPU or data-platform spend who cannot connect cost to product value, workload ownership and safe action.</p><ul><li>Cost and ownership baseline</li><li>Unit-economics decision model</li><li>30-day action and control plan</li></ul><a class="button" href="/services/cloud-ai-economics/">Inspect the review</a></article>
</div></div></section>
<section class="section alt"><div class="wrap"><span class="badge">How the work is evidenced</span><h2>A traceable review, not a generic recommendation.</h2><div class="grid-3"><article class="card"><h3>Source register</h3><p>Every material observation points to supplied architecture, policy, test, invoice, usage or public-source evidence.</p></article><article class="card"><h3>Decision boundary</h3><p>The report separates observed facts, working hypotheses, missing evidence and decisions requiring a named owner.</p></article><article class="card"><h3>Verification record</h3><p>Changes and tests are recorded so another reviewer can reproduce the conclusion without relying on presentation alone.</p></article></div></div></section>
<section class="section"><div class="wrap grid-2"><div><span class="badge">Public portfolio</span><h2>See representative deliverables before a sales conversation.</h2><p>The portfolio includes redacted structures, sample decision records and this website's own production remediation. It does not present simulations as customer outcomes.</p><a class="button secondary" href="/portfolio/">Open the evidence portfolio</a></div><div class="card"><h3>Fit signals</h3><ul><li>A production decision is near, but evidence is scattered.</li><li>AI or cloud cost is rising without accountable unit economics.</li><li>Security, finance and product teams use different decision criteria.</li><li>A board, customer or procurement reviewer needs a defensible record.</li></ul></div></div></section>
<section class="section alt"><div class="wrap card"><h2>Unsure which decision comes first?</h2><p>Submit the business problem, current stage and public website. The fit review identifies the relevant evidence boundary without requesting credentials or confidential records.</p><a class="button" href="/free-business-review/">Request guided scoping</a></div></section>'''

PRICING_BODY = '''
<section class="section"><div class="wrap"><span class="badge">Three starting paths</span><h2>Choose one decision. Confirm scope before purchase.</h2><div class="grid-3">
<article class="card"><p class="kicker">Primary</p><h3>Production AI Readiness</h3><p>Independent evidence review before an AI pilot, agent or workflow receives production responsibility.</p><ul><li>Five decision domains</li><li>Gap and evidence register</li><li>Executive readout</li></ul><p><strong>Price:</strong> confirmed after the fit review because system count, evidence condition and test scope change the work.</p><a class="button" href="/free-business-review/?offer=production-readiness">Confirm fit</a></article>
<article class="card"><p class="kicker">Secondary</p><h3>Cloud &amp; AI Economics</h3><p>Decision review for rising cloud, LLM, model, GPU and data-platform cost.</p><ul><li>Cost-owner baseline</li><li>Unit-economics model</li><li>Prioritized action plan</li></ul><p><strong>Price:</strong> confirmed after the fit review because billing sources, workloads and allocation maturity determine scope.</p><a class="button" href="/free-business-review/?offer=cloud-ai-economics">Confirm fit</a></article>
<article class="card"><p class="kicker">When the route is unclear</p><h3>Guided Scoping</h3><p>A short public-information review to identify whether readiness, economics or another specialist is the correct next step.</p><ul><li>No credentials requested</li><li>No customer data required</li><li>Clear fit or no-fit answer</li></ul><p><strong>Price:</strong> no charge for initial fit confirmation.</p><a class="button" href="/free-business-review/?offer=guided-scoping">Request scoping</a></article>
</div></div></section>
<section class="section alt"><div class="wrap grid-2"><div><h2>What a proposal must state</h2><ul><li>Decision question and system boundary</li><li>Evidence expected from each owner</li><li>Safe test boundaries and exclusions</li><li>Named outputs and delivery window</li><li>Price, taxes and payment terms</li></ul></div><div class="card"><h3>Before confidential evidence</h3><p>The public form is for fit confirmation only. Credentials, regulated records, customer data and production exports require an agreed secure exchange route.</p><p>No public page represents this work as certification, legal advice, penetration testing or a guaranteed cost/risk outcome.</p></div></div></section>'''

FORM_BODY = '''
<section class="section"><div class="wrap grid-2"><div><span class="badge">One intake</span><h2>Describe the decision, not a service code.</h2><p>We use the information only to confirm whether the problem fits Production AI Readiness, Cloud &amp; AI Economics or a specialist referral.</p><div class="card"><h3>Representative output</h3><p><strong>Evidence boundary:</strong> what can be reviewed safely.</p><p><strong>Decision route:</strong> readiness, economics or no-fit.</p><p><strong>Next action:</strong> a named evidence request and proposed scope.</p><small>Representative sample — not customer evidence.</small></div></div>
<form id="lostLeadAuditForm" class="card form-stack" action="/api/lead" method="POST"><div class="honeypot" aria-hidden="true"><label>Company website address<input name="company_website" tabindex="-1" autocomplete="off"></label></div>
<input name="form_loaded_at" id="form_loaded_at" type="hidden"><input name="business_name" id="business_name" type="hidden" value="Website submitted for review"><input name="vertical" type="hidden" value="other"><input name="package_context" id="package_context" type="hidden"><input name="service_context" id="service_context" type="hidden"><input name="landing_page" type="hidden"><input name="referrer" type="hidden"><input name="utm_source" type="hidden"><input name="utm_medium" type="hidden"><input name="utm_campaign" type="hidden">
<label>Work email<input name="prospect_email" type="email" autocomplete="email" required></label><label>Website<input name="website" type="url" placeholder="https://company.com" required></label><label>Decision to review<select name="primary_issue"><option value="Not sure">Not sure yet</option><option value="Production AI readiness">Production AI readiness</option><option value="Cloud and AI economics">Cloud and AI economics</option></select></label><label>Context (optional)<textarea name="specific_notes" rows="5" maxlength="1000" placeholder="What is changing, what decision is blocked, and when is it needed?"></textarea></label>
<button class="button" id="auditSubmitButton" type="submit">Request fit review</button><p class="small">Do not submit passwords, customer data or regulated records. See <a href="/privacy">Privacy</a>.</p><div id="auditSuccess" class="notice success" hidden role="status"></div><div id="auditError" class="notice error" hidden role="alert"></div></form></div></section>
<script src="/js/focused-intake.js?v=20261006b"></script>'''

READINESS_BODY = '''
<section class="section"><div class="wrap grid-2"><div><span class="badge">Decision trigger</span><h2>The system can demonstrate value, but the release evidence is incomplete.</h2><p>This review is designed for founders, CTOs, product owners, risk leaders and operating teams preparing to give an AI system real responsibility. It tests whether the evidence supports that decision. The work does not assume that a successful demo proves reliability, security, authority or recoverability.</p><p>A useful starting point is a named system, intended users, business consequence, current release stage and the evidence already available. The review then separates what is observed from what the team believes, and turns missing evidence into owned actions.</p></div><div class="card"><h3>Five decision domains</h3><ol><li>Outcome and evaluation evidence</li><li>Authority and human oversight</li><li>Data, security and supplier boundaries</li><li>Failure response, rollback and ownership</li><li>Consumption, cost and operating viability</li></ol></div></div></section>
<section class="section alt"><div class="wrap"><span class="badge">Method</span><h2>Four stages create a defensible release record.</h2><div class="grid-2"><article class="card"><h3>1. Frame the decision</h3><p>Document the intended outcome, users, system boundary, material consequences and the exact decision due. A readiness review fails when it becomes an open-ended architecture assessment, so scope is tied to one release or responsibility change.</p></article><article class="card"><h3>2. Inspect the evidence</h3><p>Trace requirements into evaluations, test summaries, access controls, data flows, vendor dependencies, incident procedures and operating owners. Evidence is labelled current, stale, missing or not applicable.</p></article><article class="card"><h3>3. Challenge failure and recovery</h3><p>Review selected failure modes, unsupported answers, tool misuse, escalation, human override and rollback using agreed safe inputs. This is not a penetration test and does not replace specialist security assurance.</p></article><article class="card"><h3>4. Decide and assign</h3><p>Issue a release, remediate or hold recommendation with conditions, owners, evidence requests and a 30-day action plan. The recommendation states limitations and unresolved dependencies.</p></article></div></div></section>
<section class="section"><div class="wrap grid-2"><div><span class="badge">Named deliverables</span><h2>What the buyer receives.</h2><ul><li>System and decision boundary</li><li>Source-linked evidence register</li><li>Evaluation and failure-mode gaps</li><li>Agent/tool authority matrix</li><li>Human review and escalation matrix</li><li>Data and supplier dependency map</li><li>Incident and rollback readiness record</li><li>Release conditions and 30-day plan</li></ul></div><div class="card"><h3>Representative deliverable</h3><p>The public portfolio shows a redacted production-readiness decision record built from this website's own release controls. It is self-tested evidence and is not presented as a customer outcome.</p><a class="button secondary" href="/portfolio/production-ai-readiness-sample/">View the sample dossier</a></div></div></section>
<section class="section alt"><div class="wrap"><h2>What this review does not claim.</h2><p>It is not a certification, legal opinion, compliance attestation, penetration test, model-safety guarantee or substitute for the accountable system owner. It does not prove an AI system is safe under every condition. It creates an evidence-backed decision record for a defined release question.</p><p>Teams that already have an independent evaluation function, complete release evidence and named operating ownership may not need this service. Teams seeking a broad transformation program, continuous managed operations or regulated legal advice require a different scope or specialist partner.</p></div></section>
<section class="section"><div class="wrap"><span class="badge">Buyer questions</span><h2>Questions the diagnostic is designed to answer.</h2><div class="grid-2"><article class="card"><h3>How do we know the pilot is ready?</h3><p>A pilot is not ready because it completed a demonstration. The decision needs agreed success and failure criteria, representative evaluation evidence, an accountable owner, human authority boundaries, incident response and a workable rollback path. The diagnostic identifies which evidence exists and which release conditions remain open.</p></article><article class="card"><h3>What if the AI agent can take actions?</h3><p>The review maps each tool, data source and consequential action to allowed scope, authentication, approval, logging, exception handling and human override. It tests the written boundary against available implementation evidence without requesting production credentials through the public intake.</p></article><article class="card"><h3>Can this support procurement or board review?</h3><p>The dossier is structured for decision-makers: the system boundary, evidence register, major gaps, accountable owners, conditions and limitations are explicit. It can support an internal review, but it does not replace a required audit, legal opinion or regulated certification.</p></article><article class="card"><h3>What happens after a hold decision?</h3><p>A hold is translated into an ordered remediation record. Each action includes the missing evidence, responsible owner, dependency and the check that would allow the decision to be reconsidered. This prevents a vague risk concern from becoming an indefinite project.</p></article></div></div></section>'''

ECON_BODY = '''
<section class="section"><div class="wrap grid-2"><div><span class="badge">Decision trigger</span><h2>Spend is rising faster than accountable value.</h2><p>This review is for founders, finance partners, engineering leaders, platform owners and product teams who can see cloud or AI cost increasing but cannot explain it by workload, product, customer, model or owner. The goal is an action-ready economic baseline, not a generic savings percentage.</p><p>The review starts with billing and usage exports, workload maps, commercial assumptions and owner interviews supplied through an agreed secure route. It does not require production credentials through the public website.</p></div><div class="card"><h3>Four economics questions</h3><ol><li>What is being consumed?</li><li>Who owns the decision?</li><li>What unit of value should cost follow?</li><li>Which action is safe now?</li></ol></div></div></section>
<section class="section alt"><div class="wrap"><span class="badge">Method</span><h2>From invoice lines to owned decisions.</h2><div class="grid-2"><article class="card"><h3>1. Establish the baseline</h3><p>Normalize the relevant cloud, model, GPU, data and platform cost into a dated scope. Separate recurring consumption, committed spend, idle capacity, transfer, storage and third-party AI charges.</p></article><article class="card"><h3>2. Map cost to owners and value</h3><p>Connect major cost pools to a workload, product, environment, business owner and useful value unit where evidence permits. Unallocated spend remains visible rather than being forced into a misleading model.</p></article><article class="card"><h3>3. Test action choices</h3><p>Compare rightsizing, scheduling, architecture, model choice, caching, retention, commitment and product-policy actions. Each action records expected benefit, risk, dependency, owner and verification method.</p></article><article class="card"><h3>4. Create the control loop</h3><p>Define thresholds, anomaly ownership, approval gates and review cadence so the first saving does not disappear after the report. Forecasts are labelled assumptions until observed.</p></article></div></div></section>
<section class="section"><div class="wrap grid-2"><div><span class="badge">Named deliverables</span><h2>What the buyer receives.</h2><ul><li>Dated cost and allocation baseline</li><li>Workload and owner map</li><li>Unit-economics decision model</li><li>Waste and uncertainty register</li><li>Prioritized action backlog</li><li>Approval and verification plan</li><li>30-day operating scorecard</li><li>Executive decision readout</li></ul></div><div class="card"><h3>Representative deliverable</h3><p>The public portfolio includes a transparent cloud-AI economics model using synthetic values. It demonstrates the structure and formulas without claiming customer savings.</p><a class="button secondary" href="/portfolio/cloud-ai-economics-sample/">View the sample model</a></div></div></section>
<section class="section alt"><div class="wrap"><h2>What this review does not claim.</h2><p>It does not guarantee a saving percentage, replace cloud-provider support, execute production shutdowns, purchase commitments or certify financial statements. Results depend on the quality of billing exports, ownership data, architecture context and the team's authority to implement actions.</p><p>Teams with mature allocation, active FinOps governance and reliable unit economics may need a targeted engineering engagement rather than this baseline review.</p></div></section>
<section class="section"><div class="wrap"><span class="badge">Buyer questions</span><h2>Questions the economics review is designed to answer.</h2><div class="grid-2"><article class="card"><h3>Why did cloud or AI cost increase?</h3><p>The review separates growth caused by useful demand from idle capacity, architecture choices, model routing, data retention, transfer, experimentation and unallocated ownership. A cost increase is not labelled waste until the workload and value context are understood.</p></article><article class="card"><h3>Which cost action is safe first?</h3><p>Candidate actions are ranked by evidence, expected value, implementation effort, service risk, data risk and reversibility. Shutting down or committing spend solely from a billing chart is excluded. The responsible workload owner must accept the action and verification rule.</p></article><article class="card"><h3>How should AI unit economics be measured?</h3><p>The useful unit depends on the product: a completed workflow, evaluated answer, resolved case, active customer or another business event. The model documents the numerator, denominator, exclusions and data gaps so finance and engineering use the same definition.</p></article><article class="card"><h3>Can this replace a FinOps platform?</h3><p>No. A platform may supply allocation, anomaly and commitment data. The review is useful when owners still need to choose the decision model, evidence boundary and action sequence. Mature teams may move directly to targeted engineering or platform operations.</p></article></div></div></section>'''

PORTFOLIO_BODY = '''
<section class="section"><div class="wrap"><span class="badge">Evidence before claims</span><h2>Two offer-specific portfolios.</h2><div class="grid-2"><article class="card"><p class="kicker">Self-tested implementation evidence</p><h3>Production AI Readiness dossier</h3><p>A representative decision record showing evidence classes, control ownership, release gates and limitations. It uses this company's own release workflow and public artifacts.</p><a class="button" href="/portfolio/production-ai-readiness-sample/">Inspect the dossier</a></article><article class="card"><p class="kicker">Synthetic model · formulas disclosed</p><h3>Cloud &amp; AI Economics model</h3><p>A sample allocation and action register showing how cost, owner, value unit, risk and verification are connected. Values are illustrative and are not customer savings.</p><a class="button" href="/portfolio/cloud-ai-economics-sample/">Inspect the model</a></article></div></div></section>
<section class="section alt"><div class="wrap"><h2>Proof labels used across this portfolio.</h2><div class="grid-3"><article class="card"><h3>Customer evidence</h3><p>Only completed delivery with measured records and written publication permission. None is currently published.</p></article><article class="card"><h3>Self-tested evidence</h3><p>Work performed on systems owned or operated by AICloudStrategist, with reproducible release records.</p></article><article class="card"><h3>Representative sample</h3><p>A transparent example that demonstrates structure or method. Synthetic values are labelled and never presented as outcomes.</p></article></div></div></section>'''

SAMPLE_READY = '''<section class="section"><div class="wrap"><span class="badge">Self-tested · not customer evidence</span><h2>Production release decision record</h2><div class="metric-row"><div><strong>Decision</strong><span>Release with measured follow-up</span></div><div><strong>Evidence</strong><span>PR, tests, deployment, live checks</span></div><div><strong>Limit</strong><span>Ranking remains an external outcome</span></div></div><h2>Evidence chain</h2><table class="compare"><thead><tr><th>Question</th><th>Evidence class</th><th>Release condition</th></tr></thead><tbody><tr><td>Is the change reviewable?</td><td>Git branch, pull request and diff</td><td>Tests pass and current head is reviewed</td></tr><tr><td>Is the intended code deployed?</td><td>Merge SHA and Cloudflare deployment</td><td>Production source matches the reviewed commit</td></tr><tr><td>Does the canonical route work?</td><td>HTTP, browser and structured-data checks</td><td>Priority pages and conversion path pass</td></tr><tr><td>Did ranking improve?</td><td>Provider-specific benchmark over time</td><td>Report only after observed recrawl and ranking evidence</td></tr></tbody></table><h2>Why this sample is useful</h2><p>It demonstrates the boundary between an engineering release and a business outcome. A deployed sitemap can be verified immediately; a search rank cannot. The same evidence discipline applies when an AI system moves from pilot to production.</p><p><a href="/visibility-methodology/">Review the public measurement methodology</a>.</p></div></section>'''

SAMPLE_ECON = '''<section class="section"><div class="wrap"><span class="badge">Synthetic model · not customer evidence</span><h2>Cloud-AI action register</h2><p>The values below are illustrative. The model demonstrates how an action is linked to an owner, risk and verification rule without implying an achieved saving.</p><table class="compare"><thead><tr><th>Cost pool</th><th>Observed baseline</th><th>Candidate action</th><th>Owner</th><th>Verification</th></tr></thead><tbody><tr><td>Model inference</td><td>₹500,000/month (synthetic)</td><td>Route low-risk requests to a smaller evaluated model</td><td>Product + ML</td><td>Cost/request and quality gate</td></tr><tr><td>GPU training</td><td>₹320,000/month (synthetic)</td><td>Schedule idle windows and require experiment owner</td><td>ML platform</td><td>Utilization and run ledger</td></tr><tr><td>Vector/data storage</td><td>₹140,000/month (synthetic)</td><td>Apply retention tier after evidence review</td><td>Data owner</td><td>Storage trend and retrieval test</td></tr></tbody></table><h2>Decision rule</h2><p>No action is accepted from percentage savings alone. The register records expected benefit, delivery cost, service risk, data risk, dependency, owner and post-change evidence. Forecasts remain assumptions until the measured period closes.</p><p><a href="/resources/cloud-ai-economics-decision-pack/">Open the detailed decision pack</a>.</p></div></section>'''

METHOD_BODY = '''<section class="section"><div class="wrap"><span class="badge">Version 1 · 6 October 2026</span><h2>A fixed benchmark prevents selective success claims.</h2><p>The commercial benchmark contains 32 unbranded problem prompts across India and selected international markets. Every prompt maps to one of the two canonical offers. Results are recorded separately for each provider because search results and AI answers differ by market, account, model and date.</p><div class="grid-3"><article class="card"><h3>Search evidence</h3><p>Record provider, locale, device, date, query, observed position and result URL. Top five means positions one through five in the inspected organic result set.</p></article><article class="card"><h3>AI evidence</h3><p>Record product, model, account state, prompt, answer date, recommendation order and cited URLs. A crawler allow rule is not a recommendation.</p></article><article class="card"><h3>Business evidence</h3><p>Join landing page, source/referrer, CTA and accepted lead. Qualification and revenue remain separate owner-maintained stages.</p></article></div><h2>Measurement cadence</h2><ul><li>Weekly: technical eligibility, sitemap, priority-route and event-collector health.</li><li>Every 28 days: unchanged Google, Bing and available AI prompt set.</li><li>Every 90 days: review service-market fit, intent ownership and evidence quality before changing the benchmark.</li></ul><p><a href="/visibility-benchmark-v1.json">Download the machine-readable benchmark</a> · <a href="/visibility-baseline-2026-10-06.json">Download the pre-release baseline</a>.</p></div></section>'''

ABOUT_BODY = '''<section class="section"><div class="wrap grid-2"><div><span class="badge">Operating identity</span><h2>AICloudStrategist is the public brand.</h2><p>AI Cloud Strategist is an allowed spaced display form. The joined form is used for the website, profiles and structured entity references to distinguish the brand from the generic job title.</p><p>The website is operated by <strong>AICLOUDSTRATEGIST PRIVATE LIMITED</strong>, an active Indian private company incorporated on 29 April 2026 under CIN <strong>U62020DC2026PTC470945</strong>.</p><p><a href="/company-details/">Review registered company details and verification sources →</a></p></div><div class="card" id="review-owner"><h3>Review ownership</h3><p><strong>Anushka Bhattacharya · Director</strong></p><p>Named review owner for the published Production AI Readiness and Cloud &amp; AI Economics methods. Public pages identify the evidence method and limitations; they do not claim unverified certifications or years of experience.</p><p><strong>Editorial rule:</strong> material claims require a source, a proof label and a review date.</p></div></div></section><section class="section alt"><div class="wrap"><h2>Verified public identities</h2><ul><li><a href="https://github.com/support-aicloudstrategist/support-aicloudstrategist.github.io">GitHub source and release record</a></li><li><a href="https://dev.to/aicloudstrategist">DEV publication profile</a></li><li><a href="https://www.youtube.com/@aicloudstrategist">YouTube channel</a></li></ul><p>No LinkedIn identity is represented. The company is not currently using LinkedIn.</p></div></section>'''

COMPANY_BODY = '''<section class="section"><div class="wrap grid-2"><div><span class="badge">Registered operator</span><h2>AICLOUDSTRATEGIST PRIVATE LIMITED</h2><dl><dt>Corporate Identity Number</dt><dd><strong>U62020DC2026PTC470945</strong></dd><dt>Company type</dt><dd>Private company limited by shares; non-government company</dd><dt>Incorporated</dt><dd>29 April 2026</dd><dt>Registrar</dt><dd>Registrar of Companies, Delhi</dd><dt>Status checked</dt><dd>Active in the public company-directory records inspected on 6 October 2026</dd></dl></div><div class="card"><h3>Registered office</h3><p>Plot No. B-311, Kh. No. 36, Ground Floor, Block B, Bawana, Delhi 110039, India.</p><p><strong>Public contact:</strong><br><a href="mailto:contact@aicloudstrategist.com">contact@aicloudstrategist.com</a><br>+91 80654 80898</p><p>This registered-office address is published for corporate and procurement identification. Service delivery is available remotely in India and selected international markets.</p></div></div></section><section class="section alt"><div class="wrap"><h2>How to verify the record</h2><p>Search the CIN in the Ministry of Corporate Affairs company/LLP master-data service. The same name, CIN, incorporation date, status and registered office were cross-checked against two MCA-derived public company directories before publication.</p><ul><li><a href="https://www.mca.gov.in/content/mca/global/en/home.html" rel="nofollow">Ministry of Corporate Affairs</a></li><li><a href="https://www.zaubacorp.com/AICLOUDSTRATEGIST-PRIVATE-LIMITED-U62020DC2026PTC470945" rel="nofollow">ZaubaCorp company record</a></li><li><a href="https://www.planetexim.net/indian-company/aicloudstrategist-private-limited/cin/U62020DC2026PTC470945.html" rel="nofollow">Planetexim company record</a></li></ul><p><strong>Accuracy boundary:</strong> public registry data can change. Buyers should use MCA master data for a current formal verification before contracting.</p></div></section>'''

PRIVACY_BODY = '''<section class="section"><div class="wrap"><span class="badge">Last updated 6 October 2026</span><h2>Who operates this website</h2><p>AICLOUDSTRATEGIST PRIVATE LIMITED (CIN U62020DC2026PTC470945) operates aicloudstrategist.com. The registered office and verification details are published on the <a href="/company-details/">company details page</a>.</p><h2>Information we collect</h2><p>The public fit-review form may collect work email, company website, decision category and the context you choose to provide. First-party measurement records page, referral, campaign and conversion events without intentionally collecting message contents in analytics.</p><h2>How information is used</h2><p>We use submitted information to assess fit, respond to the enquiry, protect the form from abuse, measure the acquisition journey and maintain operational records. Do not submit passwords, secrets, regulated data or confidential production exports through the public form.</p><h2>Sharing and retention</h2><p>Information may be processed by infrastructure and communication providers needed to host the site, protect the service and deliver the requested response. We do not sell enquiry data. Records are retained only as long as needed for response, security, accounting and legal obligations.</p><h2>Your requests</h2><p>To request access, correction or deletion, email <a href="mailto:contact@aicloudstrategist.com">contact@aicloudstrategist.com</a>. Applicable legal retention obligations may limit deletion.</p></div></section>'''

TERMS_BODY = '''<section class="section"><div class="wrap"><span class="badge">Last updated 6 October 2026</span><h2>Website operator</h2><p>This website is operated by AICLOUDSTRATEGIST PRIVATE LIMITED, CIN U62020DC2026PTC470945. Registered-office and verification information appears on the <a href="/company-details/">company details page</a>.</p><h2>Public information and samples</h2><p>Website content is general business information. Representative and self-tested artifacts are labelled and are not customer outcomes, guarantees, certifications, legal opinions, security attestations or financial advice.</p><h2>Engagements</h2><p>A website enquiry does not create a consulting engagement. Scope, deliverables, responsibilities, fees, taxes, confidentiality, data handling and acceptance criteria must be agreed in a written proposal or contract before paid work begins.</p><h2>Results and external platforms</h2><p>Search rankings, AI-assistant recommendations, savings, revenue, compliance and business outcomes are not guaranteed. External providers control crawling, ranking, citation, availability and account access.</p><h2>Permitted use</h2><p>You may use public checklists and methods for internal evaluation with attribution where a licence is stated. You may not misrepresent samples as customer proof, remove proof labels or use the site to submit malicious content.</p><h2>Contact</h2><p>Questions about these terms may be sent to <a href="mailto:contact@aicloudstrategist.com">contact@aicloudstrategist.com</a>.</p></div></section>'''

RESOURCE_BODY = '''<section class="section"><div class="wrap"><span class="badge">Two bounded topic clusters</span><h2>Start with the commercial decision, then use only the supporting evidence you need.</h2><div class="grid-2"><article class="card"><h3>Production AI readiness</h3><ul><li><a href="/resources/global-ai-pilot-production-go-no-go-decision-record-template/">Production go/no-go record</a></li><li><a href="/resources/global-ai-pilot-model-evaluation-regression-drift-faq/">Evaluation and drift questions</a></li><li><a href="/resources/global-ai-pilot-human-override-escalation-matrix/">Human override matrix</a></li><li><a href="/resources/global-enterprise-ai-agent-access-review-evidence-checklist/">Agent access review</a></li><li><a href="/resources/global-ai-pilot-rollback-readiness-checklist/">Rollback readiness</a></li></ul><a class="button" href="/services/production-ai-readiness/">Return to the commercial owner</a></article><article class="card"><h3>Cloud &amp; AI economics</h3><ul><li><a href="/resources/cloud-ai-economics-decision-pack/">Economics decision pack</a></li><li><a href="/resources/ai-cost-savings-claim-boundary-worksheet/">Savings-claim boundary</a></li><li><a href="/resources/global-ai-agent-cost-overrun-owner-evidence-checklist/">AI cost owner evidence</a></li><li><a href="/resources/global-enterprise-ai-cost-anomaly-approval-runbook/">Cost anomaly approval runbook</a></li><li><a href="/resources/kubernetes-namespace-cost-owner-dashboard-demo/">Namespace owner dashboard demo</a></li></ul><a class="button" href="/services/cloud-ai-economics/">Return to the commercial owner</a></article></div></div></section>'''

PAGES = {
    "index.html": shell("Production AI Readiness & Cloud AI Economics | AICloudStrategist", "Independent evidence reviews for production AI readiness and cloud AI economics in India and worldwide.", f"{BASE}/", "Make the next AI or cloud decision with evidence.", "India-first · international delivery", "AICloudStrategist helps mid-market and scale-up teams decide whether an AI system is ready for production and whether cloud/AI spend has accountable economics.", HOME_BODY, schema={"@context":"https://schema.org","@type":"WebSite","@id":f"{BASE}/#website","name":BRAND,"url":f"{BASE}/","publisher":{"@id":f"{BASE}/#organization"}}),
    "pricing/index.html": shell("Production AI and Cloud Economics Engagements | AICloudStrategist", "Two focused evidence reviews and guided scoping for production AI readiness and cloud AI economics.", f"{BASE}/pricing/", "Two focused reviews. One clear starting decision.", "Scope and commercial model", "Engagement scope is confirmed only after the system boundary, evidence condition and decision deadline are understood.", PRICING_BODY),
    "free-business-review/index.html": shell("Request an AI or Cloud Decision Fit Review | AICloudStrategist", "Request a fit review for production AI readiness or cloud AI economics without sharing credentials or confidential data.", f"{BASE}/free-business-review/", "Confirm the right evidence review before sharing sensitive material.", "Guided scoping", "Describe the decision that is blocked. We will confirm fit, evidence boundaries and the next safe step.", FORM_BODY),
    "services/production-ai-readiness/index.html": shell("Production AI Readiness Diagnostic India | AICloudStrategist", "Independent production AI readiness review covering evaluation, authority, security, recovery, economics and release evidence.", f"{BASE}/services/production-ai-readiness/", "Production AI Readiness Diagnostic", "Primary offer · India and international delivery", "A fixed-scope evidence review before an AI pilot, agent or workflow receives production responsibility.", READINESS_BODY, schema={"@context":"https://schema.org","@type":"Service","@id":f"{BASE}/services/production-ai-readiness/#service","name":"Production AI Readiness Diagnostic","provider":{"@id":f"{BASE}/#organization"},"areaServed":["India","Worldwide"],"audience":{"@type":"BusinessAudience","audienceType":"Mid-market and scale-up technology teams"},"serviceType":"Independent production AI readiness evidence review"}),
    "services/cloud-ai-economics/index.html": shell("Cloud and AI Economics Review | AICloudStrategist", "Independent cloud and AI economics review for rising cloud, model, GPU and data-platform spend.", f"{BASE}/services/cloud-ai-economics/", "Cloud & AI Economics Review", "Second focus offer · India and international delivery", "Build a dated cost, ownership and unit-economics baseline before purchasing more capacity or cutting workloads.", ECON_BODY, schema={"@context":"https://schema.org","@type":"Service","@id":f"{BASE}/services/cloud-ai-economics/#service","name":"Cloud and AI Economics Review","provider":{"@id":f"{BASE}/#organization"},"areaServed":["India","Worldwide"],"audience":{"@type":"BusinessAudience","audienceType":"Finance, engineering and product leaders"},"serviceType":"Cloud and AI cost ownership and decision review"}),
    "portfolio/index.html": shell("Evidence Portfolio | AICloudStrategist", "Representative, self-tested and transparently labelled evidence for production AI readiness and cloud AI economics.", f"{BASE}/portfolio/", "Inspect the method and deliverables before a sales conversation.", "Public evidence portfolio", "Every artifact states whether it is customer evidence, self-tested evidence or a representative sample.", PORTFOLIO_BODY),
    "portfolio/production-ai-readiness-sample/index.html": shell("Production AI Readiness Sample Dossier | AICloudStrategist", "Self-tested sample showing production release evidence, decision boundaries and verification controls.", f"{BASE}/portfolio/production-ai-readiness-sample/", "Production AI readiness sample dossier", "Self-tested evidence · not a customer result", "A compact example of how reviewable change, deployment evidence and external outcomes are separated.", SAMPLE_READY),
    "portfolio/cloud-ai-economics-sample/index.html": shell("Cloud AI Economics Sample Model | AICloudStrategist", "Transparent synthetic cost and action model for cloud and AI economics decisions.", f"{BASE}/portfolio/cloud-ai-economics-sample/", "Cloud & AI economics sample model", "Representative sample · synthetic values", "A practical structure for linking spend, ownership, action risk and post-change verification.", SAMPLE_ECON),
    "visibility-methodology/index.html": shell("Search and AI Visibility Measurement Method | AICloudStrategist", "Public methodology for measuring problem-based rankings, AI recommendations and search-to-lead conversion.", f"{BASE}/visibility-methodology/", "How AICloudStrategist measures search and AI visibility", "Public measurement contract", "A fixed, provider-specific benchmark with evidence, limitations and a declared review cadence.", METHOD_BODY),
    "about/index.html": shell("About AICloudStrategist | Evidence Ownership and Public Identity", "Public brand identity, review ownership, proof policy and verified profiles for AICloudStrategist.", f"{BASE}/about/", "Independent evidence for production AI and cloud decisions.", "About and review ownership", "The public record separates verified identity, owned methods, representative samples and facts still awaiting official verification.", ABOUT_BODY),
    "company-details/index.html": shell("Registered Company Details | AICloudStrategist", "Registered legal identity, CIN, office and verification sources for AICLOUDSTRATEGIST PRIVATE LIMITED.", f"{BASE}/company-details/", "Registered company details", "Legal identity and procurement verification", "A public identity record for buyers, suppliers and search or AI systems that need to distinguish the company from a generic job title.", COMPANY_BODY),
    "privacy": shell("Privacy Notice | AICloudStrategist", "How AICLOUDSTRATEGIST PRIVATE LIMITED handles website enquiries and first-party measurement.", f"{BASE}/privacy", "Privacy notice", "Website enquiries and measurement", "What the website collects, why it is used and how to make a data request.", PRIVACY_BODY),
    "terms": shell("Website Terms | AICloudStrategist", "Website and engagement terms for AICloudStrategist, operated by AICLOUDSTRATEGIST PRIVATE LIMITED.", f"{BASE}/terms", "Website terms", "Public information and engagement boundaries", "The conditions that apply to public materials, enquiries and proposed consulting work.", TERMS_BODY),
    "resources/index.html": shell("Production AI and Cloud Economics Resources | AICloudStrategist", "A curated evidence library supporting production AI readiness and cloud AI economics decisions.", f"{BASE}/resources/", "A focused evidence library for two buyer decisions.", "Curated resources", "Supporting pages are grouped under one canonical commercial owner for each problem instead of competing as separate offers.", RESOURCE_BODY),
}

FOCUSED_INTAKE_JS = r'''(function(){
  var form=document.getElementById('lostLeadAuditForm'); if(!form)return;
  var ok=document.getElementById('auditSuccess'),err=document.getElementById('auditError'),button=document.getElementById('auditSubmitButton');
  var params=new URLSearchParams(location.search),attr=window.aicsAttribution||{};
  form.elements.form_loaded_at.value=String(Date.now());
  form.elements.package_context.value=params.get('offer')||''; form.elements.service_context.value=params.get('service')||'';
  ['landing_page','referrer','utm_source','utm_medium','utm_campaign'].forEach(function(k){if(form.elements[k])form.elements[k].value=attr[k]||params.get(k)||'';});
  form.addEventListener('submit',async function(e){e.preventDefault();ok.hidden=true;err.hidden=true;if(!form.checkValidity()){form.reportValidity();return;}
    var payload=Object.fromEntries(new FormData(form).entries());try{payload.business_name=new URL(payload.website).hostname.replace(/^www\./,'');}catch(_){payload.business_name=payload.website;}
    payload.notes=[payload.primary_issue,payload.specific_notes].filter(Boolean).join(' · ');button.disabled=true;button.textContent='Submitting securely…';
    try{var response=await fetch('/api/lead',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}),result=await response.json().catch(function(){return{};});if(!response.ok||!result.ok)throw new Error(result.error||'Submission failed');ok.textContent='Request received. Reference: '+result.lead_id+'. We will reply by email.';ok.hidden=false;form.reset();if(window.aicsAnalytics)window.aicsAnalytics.track('form_submit_success',{props:{form:'focused_fit_review',offer:payload.package_context||payload.primary_issue||''}});}catch(ex){err.textContent='The request could not be delivered. Retry or email contact@aicloudstrategist.com.';err.hidden=false;if(window.aicsAnalytics)window.aicsAnalytics.track('form_submit_error',{props:{form:'focused_fit_review'}});}finally{button.disabled=false;button.textContent='Request fit review';}
  });
})();'''

BENCHMARK = {
    "schema_version": 1,
    "benchmark_id": "aics-organic-visibility-v1",
    "published": "2026-10-06",
    "brand": BRAND,
    "target": "Observed top-five placement for each fixed query/provider/market combination; no universal guarantee.",
    "markets": ["India", "United States", "United Kingdom", "Singapore", "United Arab Emirates"],
    "providers": ["Google", "Bing", "ChatGPT", "Gemini", "Claude", "Perplexity"],
    "queries": [
        {"id":"R01","offer":"production-ai-readiness","market":"India","text":"how to know if an AI pilot is ready for production"},
        {"id":"R02","offer":"production-ai-readiness","market":"India","text":"independent AI production readiness assessment India"},
        {"id":"R03","offer":"production-ai-readiness","market":"Global","text":"AI agent human oversight and rollback readiness review"},
        {"id":"R04","offer":"production-ai-readiness","market":"Global","text":"AI pilot go no go evidence review"},
        {"id":"R05","offer":"production-ai-readiness","market":"United Kingdom","text":"production AI governance evidence review UK"},
        {"id":"R06","offer":"production-ai-readiness","market":"Singapore","text":"AI system production readiness consultant Singapore"},
        {"id":"R07","offer":"production-ai-readiness","market":"United States","text":"independent AI agent release readiness review"},
        {"id":"R08","offer":"production-ai-readiness","market":"United Arab Emirates","text":"AI production risk evidence review UAE"},
        {"id":"R09","offer":"production-ai-readiness","market":"India","text":"AI pilot evaluation evidence checklist for production India"},
        {"id":"R10","offer":"production-ai-readiness","market":"Global","text":"AI agent access control and human approval review"},
        {"id":"R11","offer":"production-ai-readiness","market":"United States","text":"AI workflow rollback and incident readiness assessment"},
        {"id":"R12","offer":"production-ai-readiness","market":"United Kingdom","text":"independent AI release evidence consultant"},
        {"id":"R13","offer":"production-ai-readiness","market":"Singapore","text":"AI governance production evidence diagnostic"},
        {"id":"R14","offer":"production-ai-readiness","market":"United Arab Emirates","text":"AI agent human authority review UAE"},
        {"id":"R15","offer":"production-ai-readiness","market":"Global","text":"what evidence is needed before deploying an AI agent"},
        {"id":"R16","offer":"production-ai-readiness","market":"India","text":"production AI go no go review for CTO India"},
        {"id":"E01","offer":"cloud-ai-economics","market":"India","text":"cloud and AI cost optimization review India"},
        {"id":"E02","offer":"cloud-ai-economics","market":"India","text":"LLM cost allocation and unit economics consultant India"},
        {"id":"E03","offer":"cloud-ai-economics","market":"Global","text":"AI model GPU cost ownership review"},
        {"id":"E04","offer":"cloud-ai-economics","market":"Global","text":"cloud AI spend is too high what should we review"},
        {"id":"E05","offer":"cloud-ai-economics","market":"United States","text":"AI FinOps cost allocation review"},
        {"id":"E06","offer":"cloud-ai-economics","market":"United Kingdom","text":"cloud AI unit economics consultant UK"},
        {"id":"E07","offer":"cloud-ai-economics","market":"Singapore","text":"cloud and AI economics review Singapore"},
        {"id":"E08","offer":"cloud-ai-economics","market":"United Arab Emirates","text":"AI cloud cost owner review UAE"},
        {"id":"E09","offer":"cloud-ai-economics","market":"India","text":"GPU and LLM spend optimization evidence review India"},
        {"id":"E10","offer":"cloud-ai-economics","market":"Global","text":"how to allocate AI model cost by product and customer"},
        {"id":"E11","offer":"cloud-ai-economics","market":"United States","text":"cloud AI cost anomaly approval review"},
        {"id":"E12","offer":"cloud-ai-economics","market":"United Kingdom","text":"LLM unit economics assessment UK"},
        {"id":"E13","offer":"cloud-ai-economics","market":"Singapore","text":"AI FinOps owner and allocation review Singapore"},
        {"id":"E14","offer":"cloud-ai-economics","market":"United Arab Emirates","text":"cloud AI economics decision consultant UAE"},
        {"id":"E15","offer":"cloud-ai-economics","market":"Global","text":"why is AI inference cost increasing and what to review"},
        {"id":"E16","offer":"cloud-ai-economics","market":"India","text":"cloud model GPU cost ownership diagnostic India"}
    ],
    "cadence": {"technical":"weekly","provider_benchmark":"every 28 days","strategy_review":"every 90 days"},
    "evidence_fields": ["provider","product_or_model","market","date","query_id","position_or_recommendation_order","cited_url","evidence_path","notes"]
}

BASELINE = {
    "schema_version": 1,
    "baseline_id": "aics-organic-discovery-2026-10-06",
    "observed_on": "2026-10-06",
    "release_state": "before the focused consolidation could be recrawled",
    "results": {
        "google": {"queries": 16, "top_5": 1, "top_10": 2},
        "bing": {"queries": 16, "top_10": 0},
        "gemini": {"prompts": 15, "recommendations": 0},
        "perplexity": {"prompts": 8, "recommendations": 0},
        "chatgpt": {"status": "untested_signed_out"},
        "claude": {"status": "untested_signed_out"},
        "google_search_console": {"period":"2026-07-04 to 2026-10-03","clicks":14,"impressions":5810,"ctr_percent":0.2,"average_position":57.1,"generative_ai_impressions":43}
    },
    "limitations": [
        "Search and AI results vary by provider, market, device, model, account and time.",
        "The observed prompt sets are finite samples and do not represent every possible problem query.",
        "A sitemap submission or crawler allow rule does not prove ranking or recommendation.",
        "The next compatible comparison occurs only after recrawl using an unchanged benchmark."
    ]
}

ALLOW = [
    "/", "/about/", "/pricing/", "/free-business-review/", "/portfolio/",
    "/portfolio/production-ai-readiness-sample/", "/portfolio/cloud-ai-economics-sample/",
    "/services/production-ai-readiness/", "/services/cloud-ai-economics/",
    "/visibility-methodology/", "/resources/", "/company-details/", "/privacy", "/terms",
    "/resources/global-ai-pilot-production-go-no-go-decision-record-template/",
    "/resources/global-ai-pilot-model-evaluation-regression-drift-faq/",
    "/resources/global-ai-pilot-human-override-escalation-matrix/",
    "/resources/global-enterprise-ai-agent-access-review-evidence-checklist/",
    "/resources/global-ai-pilot-rollback-readiness-checklist/",
    "/resources/cloud-ai-economics-decision-pack/",
    "/resources/ai-cost-savings-claim-boundary-worksheet/",
    "/resources/global-ai-agent-cost-overrun-owner-evidence-checklist/",
    "/resources/global-enterprise-ai-cost-anomaly-approval-runbook/",
    "/resources/kubernetes-namespace-cost-owner-dashboard-demo/",
    "/resources/uae-healthtech-cloud-trust-executive-summary/",
    "/resources/europe-saas-ai-governance-evidence-diagnostic-package/",
]

def route_for(path):
    rel = path.relative_to(ROOT).as_posix()
    if rel == "index.html": return "/"
    if rel.endswith("/index.html"): return "/" + rel[:-10]
    if rel.endswith(".html"): return "/" + rel[:-5] + "/"
    return None

for rel, content in PAGES.items():
    path = ROOT / rel; path.parent.mkdir(parents=True, exist_ok=True); path.write_text(content, encoding="utf-8")

# Canonical duplicate files stay out of search and redirect through _redirects.
for alias, canonical in (("pricing.html", "pricing/index.html"), ("free-business-review.html", "free-business-review/index.html"), ("about.html", "about/index.html"), ("resources.html", "resources/index.html")):
    (ROOT / alias).write_text((ROOT / canonical).read_text(encoding="utf-8").replace('content="index,follow,max-image-preview:large"', 'content="noindex,follow"'), encoding="utf-8")

(ROOT / "js/focused-intake.js").write_text(FOCUSED_INTAKE_JS, encoding="utf-8")
(ROOT / "visibility-benchmark-v1.json").write_text(json.dumps(BENCHMARK, indent=2) + "\n", encoding="utf-8")
(ROOT / "visibility-baseline-2026-10-06.json").write_text(json.dumps(BASELINE, indent=2) + "\n", encoding="utf-8")
(ROOT / "seo/indexable-routes.txt").write_text("\n".join(ALLOW) + "\n", encoding="utf-8")
sitemap_lines = ['<?xml version="1.0" encoding="UTF-8"?>', '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">']
for route in ALLOW:
    sitemap_lines.append(f"  <url><loc>{BASE}{route}</loc><lastmod>2026-10-06</lastmod></url>")
sitemap_lines.append("</urlset>")
(ROOT / "sitemap.xml").write_text("\n".join(sitemap_lines) + "\n", encoding="utf-8")

llms = f'''# {BRAND}\n\n> Independent production AI readiness and cloud AI economics reviews. India-first, available internationally.\n\n## Canonical services\n- [Production AI Readiness]({BASE}/services/production-ai-readiness/): evaluation, authority, security, recovery, economics and release evidence.\n- [Cloud and AI Economics]({BASE}/services/cloud-ai-economics/): cost ownership, allocation, unit economics and safe action planning.\n\n## Evidence\n- [Portfolio]({BASE}/portfolio/): proof labels and representative deliverables.\n- [Production readiness sample]({BASE}/portfolio/production-ai-readiness-sample/): self-tested release dossier, not customer evidence.\n- [Cloud economics sample]({BASE}/portfolio/cloud-ai-economics-sample/): synthetic model with disclosed assumptions.\n- [Visibility methodology]({BASE}/visibility-methodology/): fixed provider-specific measurement contract.\n\n## Company\n- [About]({BASE}/about/): public identity, review ownership and verified profiles.\n- [Registered company details]({BASE}/company-details/): legal name, CIN, registered office and verification sources.\n- [Pricing and scope]({BASE}/pricing/): two focused engagement paths and guided scoping.\n- [Request a fit review]({BASE}/free-business-review/): public-information intake; do not submit credentials or confidential data.\n\n## Proof policy\nCustomer outcomes are published only after measured delivery and written consent. Current portfolio assets are labelled as self-tested evidence or representative samples. Search ranking and AI recommendation are measured external outcomes, never guarantees.\n'''
(ROOT / "llms.txt").write_text(llms, encoding="utf-8")
print(f"Wrote {len(PAGES)} focused pages and retained {len(ALLOW)} indexable routes. Middleware owns legacy noindex headers.")
